Repository Relicta-Team/ReSDK_A3.vr, pull requests merged in 2023-09, with the labels that each got.

#138 Обновлена карта test_govna, добавлены новые объекты в библиотеку
  Src/Editor/Bin/Maps/test_govna.cpp
  Src/host/GameObjects/Decors/BigWalls.sqf
  Src/host/GameObjects/Decors/Houses.sqf
  Src/host/GameObjects/Decors/Ruins.sqf
  Src/host/GameObjects/Structures/Constructions/Construction.sqf
  Src/host/GameObjects/Structures/Constructions/Fences.sqf
  Src/host/GameObjects/Structures/Constructions/Floors.sqf
  Src/host/GameObjects/Structures/Constructions/Garbages.sqf
  Src/host/GameObjects/Structures/Constructions/Houses.sqf
  Src/host/GameObjects/Structures/Constructions/MetalConstruction.sqf
  Src/host/GameObjects/Structures/Constructions/Pipes.sqf
  Src/host/GameObjects/Structures/Constructions/Walls.sqf
  Src/host/GameObjects/Structures/Electronics/Lamps/Electrical.sqf
  Src/host/GameObjects/Structures/Furniture/Beds.sqf
  Src/host/GameObjects/Structures/Furniture/Shelfs.sqf
  Src/host/GameObjects/Structures/Furniture/Tables.sqf
  Src/host/GameObjects/Structures/Interiors/SmallDecorations.sqf
  Src/host/GameObjects/Structures/Lighting/Campfires.sqf
  Src/host/MapManager/Maps/test_govna.sqf
Labels: Feature

#145 Добавлено: работа с музыкой и идеологии Грязноямска
  .gitignore
  CfgSounds.hpp
  Resources/music/lobby/Atrium Carceri - Reselected.ogg
  Resources/music/lobby/K.Stanislavsky - Now Im Ready.ogg
  Resources/music/round/common_end1.ogg
  Resources/music/round/end_newarmy.ogg
  Resources/music/round/end_tutu.ogg
  Resources/music/round/endround1.ogg
  Resources/music/round/endround2.ogg
  Resources/music/round/kingpin.ogg
  Resources/music/round/rashod.ogg
  Resources/music/round/start_1.ogg
  Resources/music/round/start_2.ogg
  Resources/music/round/start_zlachnik.ogg
  Resources/music/round/start_zlachnik_bandit.ogg
  Resources/sounds/effects/bell.ogg
  Resources/sounds/events/event_end_1.ogg
  Src/CHANGELOGS.txt
  Src/REVISION
  Src/client/ClientData/VersionViewer.sqf
  Src/client/ProxyItems/ConfigProxyItems.sqf
  Src/client/ProxyItems/Exported.h
  Src/client/SoundSystem/Music.hpp
  Src/client/loader.hpp
  Src/fn_init.sqf
  Src/host/ClientManager/cmds/EditorAndDebug.sqf
  Src/host/GameEvents/DirtpitEvents.sqf
  Src/host/GameModes/BasicDefines.sqf
  Src/host/GameModes/CommonGameAspects.sqf
  Src/host/GameModes/Dirtpit/BaseGamemode.sqf
  Src/host/GameModes/Dirtpit/GM_Extended.sqf
  Src/host/GameModes/Dirtpit/GM_OldNewOrder.sqf
  Src/host/GameModes/Dirtpit/StationRoles.sqf
  Src/host/GameModes/Saloon/GM_Saloon.sqf
  Src/host/GameModes/loader.hpp
  Src/host/GameObjects/Items/Clothes/cloth.sqf
  Src/host/GameObjects/Items/Lighting/Natural.sqf
  Src/host/GameObjects/Items/MeleeWeapons/Axes.sqf
  Src/host/GameObjects/Items/MeleeWeapons/NonCategory.sqf
  Src/host/GameObjects/Items/Stackable/Stack.sqf
  Src/host/GameObjects/Mobs/Mob_Tasks.sqf
  Src/host/GameObjects/Structures/Electronics/GeneratorParts.sqf
  Src/host/GameObjects/Structures/Electronics/Shields.sqf
  Src/host/GamemodeManager/Gamemode_RoundManager.sqf
  Third-party/SoundConfigCreator/soundConfigCreator.exe
  musicdef.cpp
Labels: Minor update, Feature

#152 Добавлены новые модели игровых предметов
  Src/client/ProxyItems/ConfigProxyItems.sqf
  Src/host/GameObjects/Items/Bodyparts/Bodyparts.sqf
  Src/host/GameObjects/Items/Clothes/cloth.sqf
  Src/host/GameObjects/Items/Food/Foods/Food.sqf
  Src/host/GameObjects/Items/RangedWeapons/AmmoBoxes.sqf
  Src/host/GameObjects/Items/RangedWeapons/Magazines.sqf
Labels: Feature

#154 Fix dev build 139115a (no changelogs)
  Src/host/GameModes/Dirtpit/BaseGamemode.sqf
  Src/host/GameModes/Dirtpit/StationRoles.sqf
  Src/host/GameModes/Saloon/GM_Saloon.sqf
  Src/host/GameObjects/Items/Food/Foods/Food.sqf
  Src/host/engine.hpp
Labels: Bug fix, Ignore changelog

#160 Stable - ReMaker 6.2, fix version file (nochangelogs)
  ReMaker/ReMaker.exe
  Src/VERSION
Labels: Bug fix, Ignore changelog

#170 Stable - Common fixes
  Src/client/WidgetSystem/widget_init.sqf
  Src/client/loader.hpp
  Src/fn_init.sqf
  Src/host/GameObjects/Items/Clothes/cloth.sqf
Labels: Bug fix, Common, Path update

#174 Dev to main
  .github/workflows/sync_changelogs.yml
  Src/Editor/Core/Core_io_helper.sqf
  Src/Editor/Widgets/Menu_functions.sqf
  Src/client/ClientStatistic/ClientStatistics_init.sqf
  Src/client/ClientStatistic/DevbuildWidget_init.sqf
  Src/host/GameModes/Dirtpit/StationRoles.sqf
  Src/host/GamemodeManager/Gamemode_RoundManager.sqf
  Src/host/engine.hpp
Labels: Ignore changelog

#177 Обновление системы загрязнения
  Resources/ui/inventory/dirt_overlay.paa
  Src/client/Inventory/functions.sqf
  Src/client/Inventory/helpers.hpp
  Src/client/Inventory/inventory_init.sqf
  Src/host/GameObjects/ConstantAndDefines/Cleanable.h
  Src/host/GameObjects/Items/Bodyparts/Bodyparts.sqf
  Src/host/GameObjects/Items/Instruments/Cleaning.sqf
  Src/host/GameObjects/Mobs/Mob.sqf
  Src/host/GameObjects/Mobs/Mob_Emotes.sqf
  Src/host/GameObjects/Mobs/Mob_Inventory.sqf
Labels: Minor update

#183 Stable - Исправления командного меню и карты Злачника
  Src/Editor/Bin/Maps/Saloon.cpp
  Src/client/ClientData/SendCommand.sqf
  Src/host/MapManager/Maps/Saloon.sqf
Labels: Bug fix, Path update

#195 ReMaker 7.0
  ReMaker/ReMaker.exe
Labels: SDK, Ignore changelog

#202 Исправление видимости чейнджлогов в лобби
  Src/host/Client/client.sqf
  Src/host/ClientManager/cmds/EditorAndDebug.sqf
  Src/host/CommonComponents/!PreInit.sqf
Labels: Bug fix

#204 Исправлено отображение текста на бумаге
  Src/client/NetDisplays/Displays/Paper.sqf
  Src/host/CommonComponents/!PreInit.sqf
Labels: Bug fix

#205 Исправлена ошибка, не позволяющая вызывать команду `getid` до начала игры.
  Src/host/ClientManager/cmds/Common.sqf
Labels: Bug fix

#211 Исправлена ошибка, позволяющая подключать свечки к держателям для факела
  Src/host/GameObjects/Structures/Lighting/Natural.sqf
Labels: Bug fix

#213 Исправлена возможная ошибка синхронизации анимаций умерших или бессознательных персонажей
  Src/host/GameObjects/Mobs/Mob_Life.sqf
Labels: Bug fix

#218 Добавлены новые подсказки при загрузке лобби
  Src/client/Lobby/lobbi_init.sqf
Labels: Feature

#215 Блокировка опций персонажа
  Src/client/ClientData/ClientData_forceWalk.sqf
  Src/client/ClientData/SendCommand.sqf
  Src/host/Client/client.sqf
  Src/host/ClientManager/cmds/Access.sqf
  Src/host/GameModes/Prey/GM_Prey.sqf
  Src/host/GameObjects/Mobs/BasicMob.sqf
  Src/host/GameObjects/Mobs/Mob.sqf
  Src/host/GameObjects/Mobs/Mob_Combat.sqf
  Src/host/GameObjects/Mobs/Mob_Interact.sqf
  Src/host/GamemodeManager/Gamemode_RoundManager.sqf
Labels: Ignore changelog
