Repository Relicta-Team/ReSDK_A3.vr, pull requests merged in 2023-12, with the labels that each got.

#249 Исправления редактора
  Src/Editor/Editor_init.sqf
  Src/Editor/MapsManager/Maps_manager_common.sqf
  Src/Editor/Widgets/Widget_ContextMenu.sqf
  Src/host/GameObjects/GameObject.sqf
  Src/host/GameObjects/Interfaces/ElectronicDevice.Interface
  Src/host/GameObjects/Structures/Lighting/Natural.sqf
  Src/host/MapManager/map_manager.sqf
  Src/host/Tools/EditorDebug/EditorDebug_datahandler.sqf
Labels: Bug fix

#250 Minor fix
  Src/host/GameObjects/Structures/Tools/Farming.sqf
Labels: Bug fix, Ignore changelog

#251 Новый режим и карта
  Src/Editor/Bin/Maps/Truba.cpp
  Src/host/GameModes/GMTruba/GMTruba_QuietShift.sqf
  Src/host/GameModes/GMTruba/GMTruba_roles.sqf
  Src/host/GameModes/GMTruba/loader.sqf
  Src/host/GameModes/scripted_loader.hpp
  Src/host/GameObjects/Items/Clothes/cloth.sqf
  Src/host/MapManager/Maps/Truba.sqf
Labels: Enhancement, Minor update
