Repository Relicta-Team/ReSDK_A3.vr, pull requests merged in 2023-10, with the labels that each got.

#230 Обновлена настройка лиц в лобби, 200+ мужских и 50+ женских лиц
  Src/client/Lobby/CharSettings.sqf
  Src/client/Lobby/debug.sqf
  Src/client/Lobby/lobbi_init.sqf
  Src/host/GameObjects/Mobs/Mob.sqf
  Src/host/GamemodeManager/Gamemode_RoundManager.sqf
  Src/host/Namings/FaceList.sqf
  Src/host/Namings/FacesHelpers.sqf
  Src/host/Namings/PrepareFaces.sqf
  Third-party/ImageConverter/optimize_paa.py
Labels: Feature

#232 Добавлена тестовая фича антистрейфа
  Src/client/StrafeLock/StrafeLock_init.sqf
  Src/client/WidgetSystem/blockedButtons.hpp
  Src/client/WidgetSystem/functions.sqf
  Src/client/loader.hpp
  Src/host/CommonComponents/Animator.sqf
  Src/host/GameObjects/Mobs/Mob.sqf
  Src/host/GameObjects/Mobs/Mob_Events.sqf
Labels: Feature

#233 Добавлена новая категория основных страниц вики, доступных из лобби
  Src/client/Lobby/SystemSettings.sqf
Labels: Feature

#237 Исправлена ошибка с неверным токеном при привязке аккаунта
  Src/host/ClientManager/cmds/Common.sqf
  Src/host/Discord/Accounts.sqf
Labels: Bug fix

#238 Исправлено открытие вики ссылок из лобби
  ReMaker/Client/description.ext
Labels: Bug fix

#240 Исправлена проблема задвоения идеологий
  Src/host/GameModes/Dirtpit/BaseGamemode.sqf
Labels: Bug fix

#241 Фикс дверей в Грязноямске
  Src/Editor/Bin/Maps/Minimap.cpp
  Src/host/MapManager/Maps/Minimap.sqf
Labels: Bug fix

#242 Новый общий модуль для алгоритмов
  Src/host/CommonComponents/Algorithm.sqf
  Src/host/CommonComponents/loader.hpp
  Src/host/engine.hpp
Labels: Ignore changelog
