Repository Relicta-Team/ReSDK_A3.vr, pull requests merged in 2024-02, with the labels that each got.

#285 Исправление дистанции прорисовки
  Src/client/ClientInit/ClientInit.sqf
Labels: Bug fix

#286 Исправление ошибок и минорные доработки
  Src/Editor/Bin/Maps/SaloonV2.cpp
  Src/Editor/Bin/Maps/Truba.cpp
  Src/host/GameModes/GMTruba/GMTruba_roles.sqf
  Src/host/GameObjects/Structures/Constructions/DirtPiles.sqf
  Src/host/MapManager/Maps/SaloonV2.sqf
  Src/host/MapManager/Maps/Truba.sqf
Labels: Bug fix

#289 Минорные исправления серверной части
  Src/Editor/Core/Core_fileWatcher.sqf
  Src/Editor/GameObjectsAssembly/GOAsm_oop_preinit.sqf
  Src/Editor/SystemTools/PerformanceObjectsTest.sqf
  Src/Editor/VisualComponents/RelativePositionEditor.sqf
  Src/Editor/VisualComponents/ScriptedEmitterEditor.sqf
  Src/Editor/Widgets/Widget_ContextMenu.sqf
  Src/Editor/Widgets/Widget_init.sqf
  Src/client/NOEngineClient/NOEngineClientInit.sqf
  Src/client/NOEngineClient/NOEngineClient_onUpdate.sqf
  Src/host/Client/client.sqf
  Src/host/GameObjects/Mobs/Mob_Interact.sqf
  Src/host/Logger/Logger_init.sqf
  Src/host/NOEngine/NOEngineInit.sqf
  Src/host/NOEngine/NOEngine_Shared.sqf
Labels: Bug fix

#299 Fixed ReMaker prebuild task
  ReMaker/BuildEvents/PREBUILD.bat
Labels: Bug fix, Ignore changelog

#305 Патч ReNode с исправлением работы с кроватями
  Documentation/ReNode/Datatypes.md
  ReNode/lib.obj
  ReNode/lib_guid
  Src/host/GameModes/BasicTask.sqf
  Src/host/GameModes/ScriptedDefines.sqf
  Src/host/GameModes/taskSystem_functions.sqf
  Src/host/GameObjects/Interfaces/ISeat.Interface
  Src/host/GameObjects/Mobs/BasicMob.sqf
  Src/host/GameObjects/Structures/Furniture/Beds.sqf
  Src/host/GameObjects/Structures/Furniture/Chairs.sqf
  Src/host/ReNode/ReNode_loadBindings.sqf
  Src/host/ReNode/_conversions.sqf
Labels: Documentation, SDK, Bug fix, Ignore changelog

#306 Исправлен узел `Строку в имя класса`
  ReNode/lib.obj
  ReNode/lib_guid
  Src/host/ReNode/_conversions.sqf
Labels: SDK, Bug fix, Ignore changelog

#309 Dev to main
  .github/workflows/all_build.yml
  .github/workflows/copyright_update.yml
  Src/Editor/Bin/copyright.sqf
  Src/Editor/VisualComponents/ScriptedEmitterEditor/ScriptedEmitterEditor_io.sqf
  Third-party/CopyrightUpdate/copyright_update.py
  Third-party/CopyrightUpdate/template.txt
Labels: Ignore changelog

#310 Доделана таска на обновление копирайтов
  .github/workflows/copyright_update.yml
  Src/host/GameModes/Saloon/GM_Saloon.sqf
  Third-party/CopyrightUpdate/copyright_update.py
Labels: Ignore changelog

#311 Fix runtime error
  Src/host/GameModes/ScriptedDefines.sqf
Labels: Bug fix, Ignore changelog

#312 Fix 2
  Src/host/GameModes/ScriptedDefines.sqf
Labels: Ignore changelog

#316 Симуляция частиц и освещения в редакторе
  Src/Editor/Core/Core_fileWatcher.sqf
  Src/Editor/Core/Core_init.sqf
  Src/Editor/Core/Core_postInit.sqf
  Src/Editor/GameObjectsAssembly/GOAsm_providers.sqf
  Src/Editor/GameObjectsLibrary/GOLib_hashData.sqf
  Src/Editor/GameObjectsLibrary/GOLib_objectManager.sqf
  Src/Editor/SystemTools/LigthSimulation.sqf
  Src/Editor/SystemTools/LigthSimulation_cfgLoader.sqf
  Src/Editor/SystemTools/SystemTools_init.sqf
  Src/Editor/VisualComponents/ScriptedEmitterEditor.sqf
  Src/Editor/VisualComponents/ScriptedEmitterEditor/ScriptedEmitterEditor_io.sqf
  Src/Editor/Widgets/Widget_ContextMenu.sqf
  Src/Editor/Widgets/Widget_init.sqf
Labels: Ignore changelog

#317 Исправление предпросмотра частиц
  Src/Editor/SystemTools/LigthSimulation.sqf
  Src/Editor/VisualComponents/ScriptedEmitterEditor.sqf
  Src/Editor/VisualComponents/ScriptedEmitterEditor/ScriptedEmitterEditor_io.sqf
Labels: Bug fix, Ignore changelog
