Repository Relicta-Team/ReSDK_A3.vr, pull requests merged in 2024-10, with the labels that each got.

#506 Обновление инспектора
  Documentation/EditorGuides/Data/editor_inspector.png
  Documentation/EditorGuides/Data/editor_inspector_mul.png
  Documentation/EditorGuides/Editor_basics.md
  Src/Editor/Core/Core_common.sqf
  Src/Editor/Editor_init.sqf
  Src/Editor/GameObjectsAssembly/GOAsm_providers.sqf
  Src/Editor/GameObjectsInspector/Inspector_functions.sqf
  Src/Editor/GameObjectsLibrary/GOLib_energy.sqf
  Src/Editor/GameObjectsLibrary/GOLib_hashData.sqf
  Src/Editor/GameObjectsLibrary/GOLib_objectManager.sqf
  Src/Editor/GameObjectsLibrary/GOLib_visual.sqf
  Src/Editor/Widgets/MouseArea.sqf
  Src/Editor/Widgets/Widget_ContextMenu.sqf
  Src/Scripts/Reditor/OOPBuilder.cs
  Src/host/GameObjects/GameObject.sqf
  Src/host/GameObjects/Items/Item.sqf
  Src/host/GameObjects/Items/Office/Books.sqf
  Src/host/GameObjects/Structures/Effects/AtmEffects.sqf
  Src/host/GameObjects/Structures/IStruct.sqf
  Src/host/engine.hpp
Labels: Documentation

#512 ReEditor 1.18, Loot template system update
  Src/Editor/Core/Core_io_helper.sqf
  Src/Editor/Editor_init.sqf
  Src/Editor/GameObjectsAssembly/GOAsm_providers.sqf
  Src/Editor/GameObjectsLibrary/GOLib_cacheStorage.sqf
  Src/Editor/GameObjectsLibrary/GOLib_init.sqf
  Src/Editor/MapsManager/Maps_manager_common.sqf
  Src/Editor/SystemTools/LootChecker.sqf
  Src/Editor/SystemTools/SystemTools_init.sqf
  Src/Editor/Widgets/Widget_init.sqf
  Src/host/FileSystem/FileSystem_init.sqf
  Src/host/GameModes/CommonTasks/PublicTasks.sqf
  Src/host/GameObjects/Structures/Furniture/Chairs.sqf
  Src/host/LootSystem/Collections/Base.yml
  Src/host/LootSystem/Collections/Test.yml
  Src/host/LootSystem/LootSystem_init.sqf
  Src/host/LootSystem/LootSystem_structs.sqf
  Src/host/LootSystem/README.md
  Src/host/LootSystem/loader.sqf
  Src/host/LootSystem/test.yml
  Src/host/UnitTests/TestsCollection/io.sqf
  Src/host/init.sqf
Labels: Documentation, Editor, Ignore changelog, Feature

#513 Fixed mark sync
  Src/Editor/GameObjectsLibrary/GOLib_cacheStorage.sqf
Labels: Bug fix, Ignore changelog

#514 Fix typo in golib::cs::initAll
  Src/Editor/GameObjectsLibrary/GOLib_cacheStorage.sqf
Labels: Bug fix, Ignore changelog

#527 Editor update, 2.18 issue fixes, improvements
  ReNode/lib.obj
  ReNode/lib_guid
  Src/Editor/Core/Core_init.sqf
  Src/Editor/GameObjectsAssembly/GOAsm_providers.sqf
  Src/Editor/GameObjectsInspector/Inspector_functions.sqf
  Src/Editor/GameObjectsLibrary/GOLib_Layers.sqf
  Src/Editor/GameObjectsLibrary/GOLib_energy.sqf
  Src/Editor/GameObjectsLibrary/GOLib_visual.sqf
  Src/Editor/SystemTools/Common.sqf
  Src/Editor/SystemTools/MeterTool.sqf
  Src/Editor/SystemTools/PerformanceObjectsTest.sqf
  Src/Editor/Widgets/Widget_ContextMenu.sqf
  Src/Editor/Widgets/Widget_WinApi.sqf
  Src/Editor/Widgets/Widget_functions.sqf
  Src/Editor/Widgets/Widget_init.sqf
  Src/client/ClientData/VersionViewer.sqf
  Src/client/ClientInit/ClientInit.sqf
  Src/client/ClientInit/DllSignCheck.sqf
  Src/client/ClientInit/_allowed_extensions.h
  Src/client/ClientStatistic/LogVariables.sqf
  Src/client/GeometryFixer/GeometryFixer_functions.sqf
  Src/client/Init.sqf
  Src/client/InputSystem/inputKeyHandlers.sqf
  Src/client/InputSystem/inputManager.sqf
  Src/client/Interactions/interact.sqf
  Src/client/Inventory/PreviewObject.sqf
  Src/client/Inventory/functions.sqf
  Src/client/NetDisplays/NetDisplays.sqf
  Src/client/WidgetSystem/blockedButtons.hpp
  Src/client/WidgetSystem/functions.sqf
  Src/fn_init.sqf
  Src/host/ClientManager/cmds/EditorAndDebug.sqf
  Src/host/CommonComponents/!PreInit.sqf
  Src/host/GameObjects/Interfaces/IContainer.Interface
  Src/host/GameObjects/Items/Office/Books.sqf
  Src/host/GamemodeManager/Gamemode_RoundManager.sqf
  Src/host/LootSystem/Collections/Test.yml
  Src/host/LootSystem/LootSystem_init.sqf
  Src/host/LootSystem/LootSystem_structs.sqf
  Src/host/LootSystem/README.md
  Src/host/NOEngine/NOEngine_ObjectManager.sqf
  Src/host/ServerInteraction/ServerInteractionInit.sqf
  Src/host/ServerInteraction/ServerInteraction_Collision.sqf
  Src/host/UnitTests/TestsCollection/io.sqf
  Src/host/Yaml/Yaml_init.sqf
  Src/host/engine.hpp
Labels: Documentation, Editor, SDK, Bug fix, Minor update

#526 Доработки после тестового запуска
  ReNode/Graphs/Army/Roles/RIntendantArmy.graph
  ReNode/Graphs/Army/Roles/RKapitanArmy.graph
  ReNode/Graphs/Army/Roles/RSoldatArmy.graph
  ReNode/Graphs/Army/Roles/RStarshinaArmy.graph
  ReNode/Graphs/Army/Roles/RVoenvrachArmy.graph
  ReNode/Graphs/Barony/Roles/RBaronBarony.graph
  ReNode/Graphs/Barony/Roles/RGeneralBarony.graph
  ReNode/Graphs/ObjectScripts/SCR_ArmyButtonScenario.graph
  ReNode/Graphs/ObjectScripts/SCR_ArmyTrevogaButton.graph
  Src/Editor/Bin/Maps/Army.cpp
  Src/host/MapManager/Maps/Army.sqf
Labels: Ignore changelog

#535 Добавления на УРНУ
  ReNode/Graphs/Army/GMArmy.graph
  ReNode/Graphs/Army/Roles/RKapitanArmy.graph
  ReNode/Graphs/Army/Roles/RNovobranetsArmy.graph
  ReNode/Graphs/Army/Roles/ROldArmy.graph
  ReNode/Graphs/Army/Roles/RProverkaArmy.graph
  ReNode/Graphs/Army/Roles/RSoldatArmy.graph
  ReNode/Graphs/ObjectScripts/SCR_ArmyTrevogaButton.graph
  Src/Editor/Bin/Maps/Army.cpp
  Src/host/MapManager/Maps/Army.sqf
Labels: Feature

#537 Stable - common fixes
  Src/fn_init.sqf
  Src/host/CraftSystem/Craft.h
  Src/host/CraftSystem/CraftSystem_init.sqf
  Src/host/CraftSystem/Craft_struct.sqf
  Src/host/CraftSystem/Crafts/Cooking.yml
  Src/host/CraftSystem/ObjectSystems/BakingOvenSystem_struct.sqf
  Src/host/CraftSystem/ObjectSystems/FryingPanSystem_struct.sqf
  Src/host/FileSystem/FileSystem_init.sqf
  Src/host/init.sqf
  Src/host/struct.hpp
Labels: Bug fix, Ignore changelog, Common
