Repository Relicta-Team/ReSDK_A3.vr, pull requests merged in 2024-05, with the labels that each got.

#391 Common update
  ReNode/lib.obj
  ReNode/lib_guid
  Src/host/CommonComponents/Gamemode.sqf
  Src/host/GameModes/BasicDefines.sqf
  Src/host/GameModes/Detective/GM_Detective.sqf
  Src/host/GameModes/Dirtpit/BaseGamemode.sqf
  Src/host/GameModes/Dirtpit/GM_TVT.sqf
  Src/host/GameModes/Saloon/GM_Saloon.sqf
  Src/host/GameModes/ScriptedDefines.sqf
  Src/host/GamemodeManager/GamemodeFunctions.sqf
  Src/host/GamemodeManager/GamemodeManager.h
  Src/host/GamemodeManager/GamemodeManager.sqf
  Src/host/GamemodeManager/Gamemode_RoundManager.sqf
  Src/host/GamemodeManager/Gamemode_deprecated.sqf
Labels: Bug fix, Ignore changelog, Common

#392 Resolved #385
  Src/host/GameModes/BasicTask.sqf
  Src/host/Logger/Logger_init.sqf
Labels: Ignore changelog, Feature, Common

#396 Минорные правки режимов Спальник, Грязноямск и Злачник
  ReNode/Graphs/Dorm/Roles/RBasicRoleSpalnik.graph
  ReNode/Graphs/Dorm/Roles/RCexDorm.graph
  ReNode/Graphs/Dorm/Roles/RCherDorm.graph
  ReNode/Graphs/Dorm/Roles/RMolDorm.graph
  ReNode/Graphs/Dorm/Roles/RSlesarDorm.graph
  ReNode/Graphs/Dorm/Roles/RTorgDorm.graph
  ReNode/Graphs/Dorm/Roles/RUchastHelperDorm.graph
  Src/Editor/Bin/Maps/Dorm.cpp
  Src/Editor/Bin/Maps/Minimap.cpp
  Src/Editor/Bin/Maps/SaloonV2.cpp
  Src/client/ProxyItems/Exported.h
  Src/host/GameObjects/Items/NOGATEG.sqf
  Src/host/GameObjects/Structures/Furniture/Chairs.sqf
  Src/host/MapManager/Maps/Dorm.sqf
  Src/host/MapManager/Maps/Minimap.sqf
  Src/host/MapManager/Maps/SaloonV2.sqf
Labels: Bug fix

#398 Кастомные анимации типа "сидя" и "стоя"
  Src/client/ClientData/ClientData.sqf
  Src/client/ClientData/ClientData_customAnims.sqf
  Src/client/InputSystem/inputKeyHandlers.sqf
  Src/host/CommonComponents/Replicator.sqf
  Src/host/GameObjects/ConstantAndDefines/Mobs.h
  Src/host/GameObjects/Interfaces/ISeat.Interface
  Src/host/GameObjects/Mobs/BasicMob.sqf
  Src/host/GameObjects/Mobs/Mob_Combat.sqf
  Src/host/GameObjects/Mobs/Mob_Emotes.sqf
  Src/host/GameObjects/Mobs/Mob_Events.sqf
  Src/host/GameObjects/Mobs/Mob_Life.sqf
  Src/host/VerbSystem/ActionsPseudonames.sqf
Labels: Bug fix, Feature

#399 Fixed logic
  Src/host/GameObjects/Mobs/Mob_Emotes.sqf
Labels: Bug fix, Ignore changelog

#400 Common animations fix
  Src/host/GameObjects/Mobs/Mob_Emotes.sqf
Labels: Bug fix, Ignore changelog, Common

#401 PREP 0.14.0
  Src/VERSION
  Src/client/ClientData/ClientData_customAnims.sqf
Labels: Ignore changelog, Minor update

#402 fix unc custom anims
  Src/host/GameObjects/Mobs/Mob_Emotes.sqf
Labels: Bug fix, Ignore changelog

#405 Общие исправления ошибок
  Src/.vscode/tasks.json
  Src/Editor/GameObjectsAssembly/GOAsm_providers.sqf
  Src/Editor/Widgets/Widget_WinApi.sqf
  Src/Scripts/Reditor/OOPBuilder.cs
  Src/VERSION
  Src/client/ClientData/ClientData_customAnims.sqf
  Src/client/Interactions/interactEmoteMenu.sqf
  Src/client/NetDisplays/Displays/Paper.sqf
  Src/client/WidgetSystem/functions.sqf
  Src/host/GameModes/BasicTask.sqf
  Src/host/GameModes/CommonGameAspects.sqf
  Src/host/GameModes/Dirtpit/BaseGamemode.sqf
  Src/host/GameModes/Dirtpit/GM_Extended.sqf
  Src/host/GameModes/Dirtpit/GM_TVT.sqf
  Src/host/GameModes/Saloon/GM_Saloon.sqf
  Src/host/GameObjects/ConstantAndDefines/Mobs.h
  Src/host/GameObjects/Interfaces/DoorBaseMethods.Interface
  Src/host/GameObjects/Interfaces/ElectronicDevice.Interface
  Src/host/GameObjects/Interfaces/IConnectibleItem.Interface
  Src/host/GameObjects/Interfaces/IConnectibleSource.Interface
  Src/host/GameObjects/Interfaces/IContainer.Interface
  Src/host/GameObjects/Interfaces/INetDisplay.Interface
  Src/host/GameObjects/Interfaces/IRadio.Interface
  Src/host/GameObjects/Interfaces/IReagentContainer.Interface
  Src/host/GameObjects/Interfaces/ISeat.Interface
  Src/host/GameObjects/Interfaces/ITrigger.Interface
  Src/host/GameObjects/Items/Office/Books.sqf
  Src/host/GameObjects/Items/RangedWeapons/RangedWeapon.sqf
  Src/host/GameObjects/Mobs/Mob.sqf
  Src/host/GameObjects/Mobs/Mob_Emotes.sqf
  Src/host/GameObjects/Mobs/Mob_Events.sqf
  Src/host/GameObjects/Mobs/Mob_Life.sqf
  Src/host/GamemodeManager/Gamemode_AllowedModes.sqf
  Src/host/oop.hpp
  Src/host/precompiled.sqf
  Third-party/BuildTools/parse_output.py
Labels: Bug fix

#407 Тестовое исправление синхронизации анимаций
  Src/host/GameObjects/Mobs/BasicMob.sqf
Labels: Bug fix

#410 Исправление ошибок
  Src/VERSION
  Src/host/GameObjects/Items/ReagentContainers/ReagentContainer.sqf
  Src/host/VerbSystem/verbsCondAndAct.sqf
  Src/host/oop.hpp
  Src/host/precompiled.sqf
Labels: Bug fix, Path update
