Repository Relicta-Team/ReSDK_A3.vr, pull requests merged in 2024-04, with the labels that each got.

#345 Resolved #344
  Src/Editor/Core/Core_settings_preInit.sqf
  Src/Editor/Simulation/Simulation_init.sqf
  Src/host/ClientManager/cmds/EditorAndDebug.sqf
  Src/host/GamemodeManager/GamemodeManager.sqf
Labels: SDK, Ignore changelog

#354 Восстановление изменений #352
  ReNode/Graphs/ObjectScripts/SCR_TestGameObjectScript.graph
  ReNode/lib.obj
  ReNode/lib_guid
  Src/CHANGELOGS.txt
  Src/Editor/Core/Core_settings_preInit.sqf
  Src/Editor/Simulation/Simulation_init.sqf
  Src/VERSION
  Src/host/ClientManager/cmds/EditorAndDebug.sqf
  Src/host/GameObjects/Mobs/Mob_Events.sqf
  Src/host/GameObjects/Mobs/Mob_Interact.sqf
  Src/host/GameObjects/Mobs/Mob_Life.sqf
  Src/host/GameObjects/ScriptedGameObject.sqf
  Src/host/GamemodeManager/GamemodeManager.sqf
  Src/host/NOEngine/NOEngine_ObjectManager.sqf
  Src/host/ReNode/ReNode_init.sqf
Labels: Ignore changelog

#361 Fix global references in gobj task
  Src/host/GameModes/CommonTasks/PublicTasks.sqf
Labels: Server, Bug fix, Ignore changelog

#367 ReNode update
  ReNode/lib.obj
  ReNode/lib_guid
  Src/host/CommonComponents/!PreInit.sqf
  Src/host/GameModes/BasicTask.sqf
  Src/host/GameModes/CommonTasks/PublicTasks.sqf
  Src/host/GameObjects/Items/Office/Books.sqf
  Src/host/GameObjects/Mobs/BasicMob.sqf
  Src/host/GameObjects/Mobs/Mob_Inventory.sqf
  Src/host/GameObjects/Mobs/Mob_Tasks.sqf
  Src/host/ReNode/_array.sqf
  Src/host/ReNode/_math.sqf
Labels: SDK, Bug fix, Ignore changelog, Feature

#378 Исправление ошибок для режима и карты Спальник
  ReNode/Graphs/Dorm/GMDorm.graph
  ReNode/Graphs/Dorm/Roles/RBasicRoleSpalnik.graph
  ReNode/Graphs/Dorm/Roles/RLekarDorm.graph
  ReNode/Graphs/Dorm/Roles/RMolDorm.graph
  ReNode/Graphs/Dorm/Roles/RUchastDorm.graph
  Src/Editor/Bin/Maps/Dorm.cpp
  Src/host/MapManager/Maps/Dorm.sqf
Labels: Bug fix, Ignore changelog

#389 Исправление проблемы с бросками предметов
  Src/host/GameObjects/Mobs/Mob_Life.sqf
Labels: Bug fix
