Repository Relicta-Team/ReSDK_A3.vr, pull requests merged in 2024-08, with the labels that each got.

#454 Переработка карты Театр
  Src/Editor/Bin/Maps/Theatre.cpp
  Src/host/GameObjects/Decors/BigFloor.sqf
  Src/host/GameObjects/Decors/BigWalls.sqf
  Src/host/GameObjects/Decors/Houses.sqf
  Src/host/GameObjects/Items/ReagentContainers/Glass.sqf
  Src/host/GameObjects/Structures/Constructions/Construction.sqf
  Src/host/GameObjects/Structures/Constructions/Pipes.sqf
  Src/host/GameObjects/Structures/Constructions/Poles.sqf
  Src/host/GameObjects/Structures/Constructions/Walls.sqf
  Src/host/GameObjects/Structures/Doors/Static/ElectronicDoors.sqf
  Src/host/GameObjects/Structures/Interiors/SmallDecorations.sqf
  Src/host/GameObjects/loader.hpp
  Src/host/MapManager/Maps/Theatre.sqf
Labels: Server, Ignore changelog, Minor update

#455 Новый режим "Баронство"
  ReNode/Graphs/Barony/GMBarony.graph
  ReNode/Graphs/Barony/Roles/RBaronBarony.graph
  ReNode/Graphs/Barony/Roles/RBrigabbatBarony.graph
  ReNode/Graphs/Barony/Roles/RGeneralBarony.graph
  ReNode/Graphs/Barony/Roles/RGriblanBarony.graph
  ReNode/Graphs/Barony/Roles/RIzbrannyyIzKanavyBarony.graph
  ReNode/Graphs/Barony/Roles/RKukhmasterBarony.graph
  ReNode/Graphs/Barony/Roles/RMasterovoy.graph
  ReNode/Graphs/Barony/Roles/RPajBarony.graph
  ReNode/Graphs/Barony/Roles/RPeshchernikBarony.graph
  ReNode/Graphs/Barony/Roles/RPodsadovnikBarony.graph
  ReNode/Graphs/Barony/Roles/RPosolKanavyBarony.graph
  ReNode/Graphs/Barony/Roles/RPosolNoryBarony.graph
  ReNode/Graphs/Barony/Roles/RSadovnikBarony.graph
  ReNode/Graphs/Barony/Roles/RSelyaninBarony.graph
  ReNode/Graphs/Barony/Roles/RSluzhivyyBarony.graph
  ReNode/Graphs/Barony/Roles/RSpetsIzNoryBarony.graph
  ReNode/Graphs/Barony/Roles/RVorishkaBarony.graph
  ReNode/Graphs/Truba/Roles/RLazutchikTruba.graph
  Src/Editor/Bin/Maps/Barony.cpp
  Src/client/LightEngine/ScriptedConfigs/SLIGHT_ITAL_LAMP_MEDIUM.sqf
  Src/client/LightEngine/ScriptedConfigs/SLIGHT_ITAL_LAMP_STRONG.sqf
  Src/client/LightEngine/ScriptedConfigs/SLIGHT_STREET_LAMP_ITAL.sqf
  Src/client/LightEngine/ScriptedEffectConfigs.sqf
  Src/client/LightEngine/ScriptedEffects.hpp
  Src/host/MapManager/Maps/Barony.sqf
Labels: Server, Minor update, Feature

#456 Роли для режима Театр
  ReNode/Graphs/Theatre/GMTheatre.graph
  ReNode/Graphs/Theatre/RArtistGroup1Theatre.graph
  ReNode/Graphs/Theatre/RArtistGroup2Theatre.graph
  ReNode/Graphs/Theatre/RAudienceRichTheatre.graph
  ReNode/Graphs/Theatre/RAudienceTheatre.graph
  ReNode/Graphs/Theatre/RBarmanTheathre.graph
  ReNode/Graphs/Theatre/RBasicRoleTheatre.graph
  ReNode/Graphs/Theatre/RGuardTheatre.graph
  ReNode/Graphs/Theatre/RHelperTheatre.graph
  ReNode/Graphs/Theatre/RMasterTheatre.graph
  ReNode/lib.obj
  ReNode/lib_guid
  Src/Editor/Bin/Maps/Theatre.cpp
  Src/host/GameObjects/Items/Clothes/cloth.sqf
  Src/host/MapManager/Maps/Theatre.sqf
Labels: Server, Minor update

#460 common gamemode theatre fixes
  ReNode/Graphs/Theatre/GMTheatre.graph
  ReNode/Graphs/Theatre/RArtistGroup1Theatre.graph
Labels: Bug fix, Ignore changelog, Common

#461 Минорные исправления режима Влага Камней
  ReNode/Graphs/Barony/GMBarony.graph
  ReNode/Graphs/Barony/Roles/RBaronBarony.graph
  ReNode/Graphs/Barony/Roles/RBrigabbatBarony.graph
  ReNode/Graphs/Barony/Roles/RGeneralBarony.graph
  ReNode/Graphs/Barony/Roles/RGriblanBarony.graph
  ReNode/Graphs/Barony/Roles/RIzbrannyyIzKanavyBarony.graph
  ReNode/Graphs/Barony/Roles/RKukhmasterBarony.graph
  ReNode/Graphs/Barony/Roles/RMasterovoy.graph
  ReNode/Graphs/Barony/Roles/RPajBarony.graph
  ReNode/Graphs/Barony/Roles/RPeshchernikBarony.graph
  ReNode/Graphs/Barony/Roles/RPodsadovnikBarony.graph
  ReNode/Graphs/Barony/Roles/RPosolKanavyBarony.graph
  ReNode/Graphs/Barony/Roles/RPosolNoryBarony.graph
  ReNode/Graphs/Barony/Roles/RSadovnikBarony.graph
  ReNode/Graphs/Barony/Roles/RSelyaninBarony.graph
  ReNode/Graphs/Barony/Roles/RSluzhivyyBarony.graph
  ReNode/Graphs/Barony/Roles/RSpetsIzNoryBarony.graph
  ReNode/Graphs/Barony/Roles/RVorishkaBarony.graph
  Src/Editor/Bin/Maps/Barony.cpp
  Src/host/MapManager/Maps/Barony.sqf
Labels: Bug fix

#462 Исправления на карте Имение Влага Камней.
  Src/Editor/Bin/Maps/Barony.cpp
  Src/host/MapManager/Maps/Barony.sqf
Labels: Bug fix

#463 Database update
  ReMaker/Deploy/SQLiteNet_x64.dll
  Src/host/Database/SQLite/SQLite_functions.sqf
  Src/host/GamemodeManager/Gamemode_AllowedModes.sqf
Labels: Server, Ignore changelog, Feature

#464 Правки режима и карты Театр
  ReNode/Graphs/ObjectScripts/SCR_TheatreButtonScenario.graph
  Src/Editor/Bin/Maps/Theatre.cpp
  Src/host/MapManager/Maps/Theatre.sqf
Labels: Server, Bug fix

#469 Таскание
  Src/client/NOEngineClient/NOEngineClientInit.sqf
  Src/client/NOEngineClient/NOEngineClient_NOGEOM_ext.sqf
  Src/client/NOEngineClient/NOEngineClient_ObjectManager.sqf
  Src/client/NOEngineClient/NOEngineClient_TransportLevel.sqf
  Src/client/NetDisplays/Displays/MobInventory.sqf
  Src/client/SyncMobData/SMD_init.sqf
  Src/host/CommonComponents/!PreInit.sqf
  Src/host/CommonComponents/ModelTransform.hpp
  Src/host/GameObjects/GameObject.sqf
  Src/host/GameObjects/Interfaces/ISeat.Interface
  Src/host/GameObjects/Items/Item.sqf
  Src/host/GameObjects/Structures/Containers/Boxes.sqf
  Src/host/GameObjects/Structures/Containers/Cabinets.sqf
  Src/host/GameObjects/Structures/Containers/Closets.sqf
  Src/host/GameObjects/Structures/Containers/Library.sqf
  Src/host/GameObjects/Structures/Tools/Farming.sqf
  Src/host/NOEngine/NOEngine_ObjectRegisterModel.sqf
  Src/host/VerbSystem/verbsCondAndAct.sqf
Labels: Minor update

#470 Пререлизные фиксы
  Src/Editor/Bin/Maps/Theatre.cpp
  Src/host/GameObjects/GameObject.sqf
  Src/host/GameObjects/Items/RangedWeapons/Ammo.sqf
  Src/host/GameObjects/Items/RangedWeapons/AmmoBoxes.sqf
  Src/host/GameObjects/Items/Traps/Trap.sqf
  Src/host/MapManager/Maps/Theatre.sqf
Labels: Bug fix

#473 Resolved #471
  Src/client/LightEngine/LightEngine.sqf
  Src/client/LightEngine/ScriptedConfigs/SLIGHT_MOB_VOMIT.sqf
  Src/client/LightEngine/ScriptedEffectConfigs.sqf
  Src/client/LightEngine/ScriptedEffects.hpp
  Src/client/LightEngine/ScriptedEffects.sqf
  Src/host/GameObjects/ConstantAndDefines/Mobs.h
  Src/host/GameObjects/Mobs/BasicMob.sqf
  Src/host/GameObjects/Mobs/Mob_Life.sqf
Labels: Feature

#479 Resolved #478
  Src/Editor/Core/Core_init.sqf
  Src/Editor/Editor_init.sqf
  Src/Editor/GameObjectsInspector/Inspector_functions.sqf
  Src/Editor/Widgets/Widget_ContextMenu.sqf
Labels: Ignore changelog

#480 Мини-правки Влага Камней
  ReNode/Graphs/ObjectScripts/SCR_BaronyTrubyEnergiya.graph
  Src/Editor/Bin/Maps/Barony.cpp
  Src/host/MapManager/Maps/Barony.sqf
Labels: Bug fix
