Repository Relicta-Team/ReSDK_A3.vr, pull requests merged in 2024-12, with the labels that each got.

#574 Resolved #572
  Src/host/GamemodeManager/Gamemode_RoundManager.sqf
Labels: Ignore changelog

#576 Исправления после тестов для режима Спальник
  ReNode/Graphs/Dorm/ObjectScripts/SCR_GuardButtonDorm.graph
  ReNode/Graphs/Dorm/Roles/RRookieGuardDorm.graph
  Src/Editor/Bin/Maps/Dorm.cpp
  Src/host/MapManager/Maps/Dorm.sqf
Labels: Bug fix, Ignore changelog

#580 Минорные правки карты Спальник
  Src/Editor/Bin/Maps/Dorm.cpp
  Src/host/MapManager/Maps/Dorm.sqf
Labels: Bug fix

#584 Фиксы режима Застолье в гостях
  ReNode/Graphs/Holiday/RBasicLateRoleHoliday.graph
  ReNode/Graphs/Holiday/RFirendHoliday.graph
  ReNode/Graphs/Holiday/RFriendGrandpa.graph
  ReNode/Graphs/Holiday/RFriendSonHoliday.graph
  ReNode/Graphs/Holiday/RFriendWife.graph
  ReNode/Graphs/Holiday/RHeadHoliday.graph
  ReNode/Graphs/Holiday/RManorOwnerHoliday.graph
  ReNode/Graphs/Holiday/ROfficerHoliday.graph
  ReNode/Graphs/Holiday/ROfficereWifeHoliday.graph
  ReNode/Graphs/Holiday/ROwnerSonHoliday.graph
  ReNode/Graphs/Holiday/ROwnerWifeHoliday.graph
  ReNode/Graphs/Holiday/RTraderHoliday.graph
Labels: Bug fix

#586 Фиксы и доработки карты режима Застолье в гостях
  Src/Editor/Bin/Maps/Holiday.cpp
  Src/host/GameObjects/Structures/Furniture/Sofas.sqf
  Src/host/MapManager/Maps/Holiday.sqf
Labels: Bug fix

#591 Исправления карты "Рукав"
  Src/Editor/Bin/Maps/Holiday.cpp
  Src/host/MapManager/Maps/Holiday.sqf
Labels: Bug fix
