Repository Relicta-Team/ReSDK_A3.vr, pull requests merged in 2024-06, with the labels that each got.

#413 Fixed class sewercoverbase damage
  Src/host/GameObjects/Structures/Effects/Teleport.sqf
Labels: Bug fix

#417 Переработка подсистемы звуков шагов
  Src/client/ClientStatistic/LogVariables.sqf
  Src/client/Interactions/interact.sqf
  Src/client/NOEngineClient/NOEngineClient_ObjectManager.sqf
  Src/client/OneSync/OneSync_steps.sqf
  Src/host/GameObjects/Items/item_worklist.cpp
  Src/host/GameObjects/Mobs/BasicMob.sqf
  Src/host/GameObjects/Mobs/Mob.sqf
  Src/host/GameObjects/Mobs/Mob_Events.sqf
  Src/host/Materials/Materials_base.sqf
Labels: Enhancement, Server

#420 Пожары
  Resources/sounds/fire/flame_1.ogg
  Resources/sounds/fire/flame_2.ogg
  Resources/sounds/fire/flame_3.ogg
  Resources/sounds/reagents/sink.ogg
  Resources/sounds/reagents/water_land.ogg
  Src/Editor/Bin/Maps/Minimap.cpp
  Src/Editor/Bin/Maps/SaloonV2.cpp
  Src/Editor/Bin/Maps/Template.cpp
  Src/client/ClientData/ClientData.sqf
  Src/client/InputSystem/inputManager.sqf
  Src/client/LightEngine/LightEngine.sqf
  Src/client/LightEngine/SEConfigHandlers.sqf
  Src/client/LightEngine/ScriptedConfigs/SLIGHT_ATMOS_FIRE_1.sqf
  Src/client/LightEngine/ScriptedConfigs/SLIGHT_ATMOS_FIRE_2.sqf
  Src/client/LightEngine/ScriptedConfigs/SLIGHT_ATMOS_FIRE_3.sqf
  Src/client/LightEngine/ScriptedConfigs/SLIGHT_ATMOS_SMOKE_1.sqf
  Src/client/LightEngine/ScriptedConfigs/SLIGHT_ATMOS_SMOKE_2.sqf
  Src/client/LightEngine/ScriptedConfigs/SLIGHT_ATMOS_SMOKE_3.sqf
  Src/client/LightEngine/ScriptedEffectConfigs.sqf
  Src/client/LightEngine/ScriptedEffects.hpp
  Src/client/LightEngine/ScriptedEffects.sqf
  Src/client/NOEngineClient/NOEngineClient_ObjectManager.sqf
  Src/client/OneSync/OneSync_steps.sqf
  Src/client/SoundSystem/Sound3d.sqf
  Src/host/Atmos/Atmos.h
  Src/host/Atmos/Atmos.hpp
  Src/host/Atmos/Atmos_ChunkStruct.sqf
  Src/host/Atmos/Atmos_debug.sqf
  Src/host/Atmos/Atmos_init.sqf
  Src/host/GameObjects/ConstantAndDefines/TimeConstants.h
  Src/host/GameObjects/GameObject.sqf
  Src/host/GameObjects/Interfaces/IContainer.Interface
  Src/host/GameObjects/Items/Bodyparts/Organs.sqf
  Src/host/GameObjects/Items/Lighting/Natural.sqf
  Src/host/GameObjects/Items/ReagentContainers/ReagentContainer.sqf
  Src/host/GameObjects/Items/Traps/Trap.sqf
  Src/host/GameObjects/Mobs/BasicMob.sqf
  Src/host/GameObjects/Mobs/Mob_Life.sqf
  Src/host/GameObjects/Structures/Effects/Atmos.sqf
  Src/host/GameObjects/Structures/Effects/Gases.sqf
  Src/host/GameObjects/Structures/Furniture/Shelfs.sqf
  Src/host/GameObjects/Structures/IStruct.sqf
  Src/host/GameObjects/Structures/Interiors/InteractibleInteriors.sqf
  Src/host/GameObjects/Structures/Lighting/Campfires.sqf
  Src/host/GameObjects/Structures/Lighting/Natural.sqf
  Src/host/MapManager/Maps/Minimap.sqf
  Src/host/MapManager/Maps/SaloonV2.sqf
  Src/host/MapManager/Maps/Template.sqf
  Src/host/Materials/Materials_base.sqf
  Src/host/MatterSystem/MatterSystem_functions.sqf
  Src/host/MatterSystem/Matters/Basic.sqf
  Src/host/NOEngine/NOEngine_ObjectRegisterModel.sqf
  Src/host/OOP_engine/oop_object.sqf
  Src/host/ServerInteraction/ServerInteractionInit.sqf
  Src/host/VerbSystem/verbsCondAndAct.sqf
  Src/host/VerbSystem/verbsDefine.sqf
  Src/host/init.sqf
Labels: Server, Minor update

#421 Доработка карт Поместье и Труба для системы пожаров
  Src/Editor/Bin/Maps/Detective.cpp
  Src/Editor/Bin/Maps/Truba.cpp
  Src/host/MapManager/Maps/Truba.sqf
  Src/host/MapManager/Maps/detective.sqf
Labels: Server, Bug fix
