Repository Relicta-Team/ReSDK_A3.vr, pull requests merged in 2024-01, with the labels that each got.

#261 Доработка карты Труба
  Src/Editor/Bin/Maps/Truba.cpp
  Src/host/MapManager/Maps/Truba.sqf
Labels: Ignore changelog

#265 Исправление Грязноямска
  Src/Editor/Bin/Maps/Minimap.cpp
  Src/host/MapManager/Maps/Minimap.sqf
Labels: Bug fix

#269 Добавил dev1l в вайтлист
  Src/host/ClientManager/functions.sqf
Labels: Ignore changelog, Feature

#271 Исправлена проверка яркости
  Src/client/ClientData/EscapeMenu.sqf
  Src/client/ClientInit/ClientInit.sqf
  Src/client/WidgetSystem/functions.sqf
Labels: Bug fix
