Repository Relicta-Team/ReSDK_A3.vr, pull requests merged in 2025-06, with the labels that each got.

#632 Stable - Исправление бага с валидацией роли
  Documentation/API/host/GamemodeManager.md
  Src/host/Client/client.sqf
  Src/host/GamemodeManager/GamemodeFunctions.sqf
  Src/host/GamemodeManager/Gamemode_RoundManager.sqf
Labels: Documentation, Bug fix

#640 Fix #635
  Src/host/CraftSystem/CraftSystemProcess.sqf
Labels: Bug fix

#645 Development
  Src/client/PersonClient/PersonClient_init.sqf
Labels: Ignore changelog

#648 Resolved #647
  Src/client/NetDisplays/Displays/Examine3d.sqf
  Src/client/PersonClient/PersonClient_init.sqf
  Src/host/GamemodeManager/Gamemode_RoundManager.sqf
Labels: Ignore changelog

#650 fix crafts
  Src/host/CraftSystem/CraftSystemProcess.sqf
Labels: Bug fix, Path update
