Repository Relicta-Team/ReSDK_A3.vr, pull requests merged in 2025-04, with the labels that each got.

#609 Маленькие изменения
  Src/host/CraftSystem/Crafts/Cooking.yml
  Src/host/CraftSystem/Crafts/Medical.yml
  Src/host/CraftSystem/Crafts/Others.yml
Labels: Ignore changelog

#614 fixed interact distance
  Src/host/GameObjects/Mobs/Mob_Interact.sqf
Labels: Bug fix, Ignore changelog

#616 Revert "fixed interact distance"
  Src/host/GameObjects/Mobs/Mob_Interact.sqf
Labels: Bug fix
